### ISSUE TITLE
Calendar day selection boxes show as rectangles, not squares

### ISSUE THREAD

**Issue by keegandonley** [eternicode/bootstrap-datepicker#1523]
In my implementation of Bootstrap datepicker, the little highlight boxes around the selected day is stretched a little - the whole thing is a bit rectangular, as opposed to all the examples, in which the highlight is a square.
My date picker: 
![screen shot 2015-08-12 at 1 21 16 pm](https://cloud.githubusercontent.com/assets/12700819/9235724/673c9e82-40f5-11e5-9169-81506771b6f0.png)
Example (for reference):
![screen shot 2015-08-12 at 1 21 01 pm](https://cloud.githubusercontent.com/assets/12700819/9235735/79b6fcc4-40f5-11e5-8312-17ca297b35df.png)
As you can see it looks like it's using a different stylesheet for some reason. I just re-compiled the less into a standalone css file and I get the same result.

**Comment by ETNOL** [comment]
Can you check with inspector to see if anything is overwriting the following rule :
```css
.datepicker table tr td, .datepicker table tr th {
    text-align: center;
    width: 30px; /* especially this width */
    height: 30px;
    border-radius: 4px;
    border: none;
}
```

**Comment by keegandonley** [comment]
@ETNOL I only see 

<pre>
.datepicker td, .datepicker th {
  text-align: center;
  width: 20px;
  height: 20px;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
  border: none;
}
</pre>

**Comment by ETNOL** [comment]
Weird. Our examples are probably from different code versions. What if you add the following rule:
```css
.datepicker table tr td, .datepicker table tr th {
    min-width: 30px;
}
```
I'm thinking that would be the most likely rule to fix your problem by forcinc all the td's and th's to be at least 30px. 

For a little explanation:

Table cells will expand as wide as necessary to fufill css rules but they will only collapse as far as their content will allow no matter what css rules are applied.  Since the demo cells appear as ~30px by ~30px, you may be able to just get away with changing those width and height values to 30px instead of 20px. Without a set width, the current table ends up with a variety of widths between ~25px and 31px based on their content. So the width:20px rule ends up doing nothing because it is smaller than the table cell's contents.
