### ISSUE TITLE
Datepicker gets incorrectly oriented

### ISSUE THREAD

**Issue by decimoseptimo** [eternicode/bootstrap-datepicker#1920]
I'm overridding two css classes

```css
.datepicker{
    padding: 12px;
}

.datepicker td {
    padding: 5px 9px !important;
}
```
### Expected behaviour
Depending on what orientation takes into account (e.g. fixed elements, browser's window only). This may or may not be a bug. But I'd expect it doesn't underlaps other elements when 'auto' oriented.

### Actual behaviour
.datepicker gets underlapped to .navbar-fixed-top
![fireshot screen capture 015 - ordenes - 192_168_1_100_9997_index_php_r order_ind](https://cloud.githubusercontent.com/assets/16873203/16106736/075c2934-334c-11e6-86ee-e40003eba421.png)

Where is positioning handled in datepicker?

### Datepicker version used

ex. 1.6.1.
