### ISSUE TITLE
Input field padding is inconsistent with other 'form-control' classes

### ISSUE THREAD

**Issue by Zooce** [eternicode/bootstrap-datepicker#686]
The title really says it all.

When you select a date from the datepicker and the input text is populated with the chosen date, the padding is inconsistent with other input text fields. I believe in the datepicker.css file, this class reads:

```css
.datepicker {
  padding: 4px;
.....
}
```

whereas in bootstrap.css:

```css
.form-control {
...
  padding: 6px 12px;
...
}
```

Tried to change this, but not sure if this is handled within the datepicker.js file.

Any thoughts?
